name: Matrix
on: [ push ]

jobs:
  node-matrix:
    # continue-on-error: false
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        node-version: [ 14, 15, 16 ]
        includes:
        - os: ubuntu-latest
          is-ubuntu: true
        - os: macos-latest
          node-version: 15
        - experimental: false
        - os: ubuntu-latest
          node-version: 16
          experimental: true
        - os: ubuntu-latest
          node-version: 17
        exclude:
        - os: ubuntu-latest
          node-version: 14
      # max-parallel: 3
      fail-fast: false
    runs-on: ${{ matrix.os  }}
    steps:
    - if: matrix.experimental == true
      run: exit 1
    - run: echo '${{ toJson(matrix) }}'
    - run: node -v
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: node -v
