name: Status Check functions
on: [ push ]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
      run: sleep 20
    - name: Runs on Failure
      if: failure()
      run: echo 'Runs only on failure'
    - name: Runs on Success
      if: success()
      run: echo 'Runs on Success'
    - name: Always runs
      #if: success() || failure()
      if: always()
      run: echo 'Always Runs'
    - name: Runs When Canceled
      if: cancelled()
      run: echo 'Runs on cancelled'

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
    - run: echo 'Job-2'
